version: "3.8"

services:
  vhost:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      
  server:
    build: ./    
    command: gunicorn --bind 0.0.0.0:5000 app:app
    expose:
      - "5000"
    environment:
      VIRTUAL_HOST: api.127.0.0.1.nip.io
    # depends_on:
    #   - mongodb

  # mongodb:
  #   image: mongo
  #   expose:
  #     - "27017"
  #   volumes:
  #     - mongodb_data:/data/db

# volumes:
#   mongodb_data:
