version: "3.8"

services:
  server:
    build: ./
    command: gunicorn --bind 0.0.0.0:5000 server:app
    expose:
      - "5000"
    # depends_on:
    #   - mongodb

  # mongodb:
  #   image: mongo
  #   expose:
  #     - "27017"
  #   volumes:
  #     - mongodb_data:/data/db

# volumes:
#   mongodb_data:
